version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  deploy:
    machine:
      enabled: true
    working_directory: ~/workspace
    steps:
      - checkout
      - run: cd ${HOME}/workspace
      - restore_cache:
          name: Restore npm cache
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i -g npm
      - run: npm install
      - save_cache:
          name: Store npm cache
          key: npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
